project:
  type: website
  output-dir: _site

website:
  title: "scDiagnostics Manuscript Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Data & Methods"
        menu:
          - href: setup.qmd
            text: "Setup & Installation"
          - href: data-access.qmd
            text: "Getting Data"
          - href: processing-covid.qmd
            text: "COVID-19 Processing"
          - href: processing-merfish.qmd
            text: "MERFISH Processing"
          - href: adding-annotations.qmd
            text: "Adding Annotations"
      - text: "Tutorials & Results"
        menu:
          - href: overview-scdiagnostics.qmd
            text: "scDiagnostics Overview"
          - href: results-simulation.qmd
            text: "Simulation"
          - href: results-brain.qmd
            text: "Zeisel Brain"
          - href: results-covid.qmd
            text: "COVID-19"
          - href: results-merfish.qmd
            text: "MERFISH"
          - href: annotation-diagnostics.qmd
            text: "Exploring Annotation Tool Diagnostics"
  repo-url: https://github.com/ccb-hms/scDiagnosticsManuscript
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true